// U17b (§3.4) — Miền email dùng-một-lần. Danh sách TĨNH, tra offline có chủ ý: gọi API bên
// thứ ba ở đường đăng ký công khai là thêm một phụ thuộc mạng vào đúng chỗ dễ bị dội tải
// nhất, và làm rò địa chỉ email của khách sang bên ngoài.
// Danh sách không bao giờ đầy đủ — nó chỉ nâng chi phí lạm dụng, không phải hàng rào tuyệt
// đối. Bổ sung dần khi thấy lạm dụng thật.
export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "10minutemail.com",
  "tempmail.com",
  "temp-mail.org",
  "throwawaymail.com",
  "yopmail.com",
  "fakeinbox.com",
  "trashmail.com",
  "getnada.com",
  "dispostable.com",
  "maildrop.cc",
  "sharklasers.com",
  "grr.la",
  "guerrillamailblock.com",
  "spam4.me",
  "mailnesia.com",
  "mytemp.email",
  "tempinbox.com",
  "emailondeck.com",
  "mohmal.com",
  "tempr.email",
  "discard.email",
  "mailcatch.com",
  "inboxbear.com",
  "spambog.com",
  "burnermail.io",
  "anonaddy.com",
  "simplelogin.io",
  "33mail.com",
  "moakt.com",
  "tmpmail.org",
  "email-temp.com",
  "luxusmail.org",
  "vomoto.com",
  "byom.de",
  "one-time.email",
  "mailtemp.net",
  "instant-mail.de",
  "tmail.ws",
  "minuteinbox.com",
  "fakemail.net",
  "tempmailo.com",
  "mail-temp.com",
  "tempemail.co",
  "nowmymail.com",
  "spamgourmet.com",
  "trbvm.com",
  "harakirimail.com",
  "incognitomail.com",
]);
